[package]
name = "dlauncher-terminal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlauncher = "0.1.1"
gtk = { version =  "0.15.5", features = ["v3_22"] }
lazy_static = "1.4.0"
log = "0.4.17"
serde_json = "1.0.81"
libc = "0.2.125"
